version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d store"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - palindrome-network

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/store
      CORS_ORIGIN: http://localhost:3001
      AUTO_SEED: "true"  # Habilita auto-seeding para facilitar evaluación
    ports:
      - "3000:3000"
    networks:
      - palindrome-network
    restart: unless-stopped

volumes:
  pgdata:

networks:
  palindrome-network:
    driver: bridge
