export const seedProducts = [
  {
    title: 'Z-Runner',
    brand: 'Abba Sports',
    description: 'Light shoes with abba pattern',
    price: 1200.0,
    imageUrl: 'https://picsum.photos/400/300?random=1',
  },
  {
    title: 'MoonDash',
    brand: 'Orbit',
    description: 'Comfort for daily running',
    price: 980.0,
    imageUrl: 'https://picsum.photos/400/300?random=2',
  },
  {
    title: 'ABBA Pro',
    brand: 'Nordic',
    description: 'ABBA limited edition',
    price: 2500.0,
    imageUrl: 'https://picsum.photos/400/300?random=3',
  },
  {
    title: 'Wave',
    brand: 'Coast',
    description: 'Casual sneakers',
    price: 800.0,
    imageUrl: 'https://picsum.photos/400/300?random=4',
  },
  {
    title: 'Echo',
    brand: 'Rebound',
    description: 'High rebound midsole',
    price: 1600.0,
    imageUrl: 'https://picsum.photos/400/300?random=5',
  },
  {
    title: 'Tango',
    brand: 'Dance',
    description: 'Designed for studio',
    price: 1100.0,
    imageUrl: 'https://picsum.photos/400/300?random=6',
  },
  {
    title: 'abba',
    brand: 'Test Brand',
    description: 'Test product for palindrome testing',
    price: 500.0,
    imageUrl: 'https://picsum.photos/400/300?random=7',
  },
  {
    title: 'ABBA One',
    brand: 'ABBA Performance',
    description: 'Edition inspired by abba with level cushioning and radar grip',
    price: 850.0,
    imageUrl: 'https://picsum.photos/400/300?random=8',
  },
  {
    title: 'ABBA Sprint',
    brand: 'ABBA Lab',
    description: 'Lightweight trainer; keywords: abba, rotor plate, civic mesh',
    price: 900.0,
    imageUrl: 'https://picsum.photos/400/300?random=9',
  },
  {
    title: 'ABBA Glide',
    brand: 'ABBA Works',
    description: 'Daily comfort. Contains palindromes: abba, level, radar',
    price: 960.0,
    imageUrl: 'https://picsum.photos/400/300?random=10',
  },
  {
    title: 'Level',
    brand: 'Level Performance',
    description: 'Edition inspired by level with level cushioning and radar grip',
    price: 1010.0,
    imageUrl: 'https://picsum.photos/400/300?random=11',
  },
  {
    title: 'Level Sprint',
    brand: 'Level Lab',
    description: 'Lightweight trainer; keywords: level, rotor plate, civic mesh',
    price: 1060.0,
    imageUrl: 'https://picsum.photos/400/300?random=12',
  },
  {
    title: 'Level Glide',
    brand: 'Level Works',
    description: 'Daily comfort. Contains palindromes: level, level, radar',
    price: 1120.0,
    imageUrl: 'https://picsum.photos/400/300?random=13',
  },
  {
    title: 'Radar',
    brand: 'Radar Performance',
    description: 'Edition inspired by radar with level cushioning and radar grip',
    price: 1170.0,
    imageUrl: 'https://picsum.photos/400/300?random=14',
  },
  {
    title: 'Radar Sprint',
    brand: 'Radar Lab',
    description: 'Lightweight trainer; keywords: radar, rotor plate, civic mesh',
    price: 1220.0,
    imageUrl: 'https://picsum.photos/400/300?random=15',
  },
  {
    title: 'Radar Glide',
    brand: 'Radar Works',
    description: 'Daily comfort. Contains palindromes: radar, level, radar',
    price: 1280.0,
    imageUrl: 'https://picsum.photos/400/300?random=16',
  },
  {
    title: 'Civic',
    brand: 'Civic Performance',
    description: 'Edition inspired by civic with level cushioning and radar grip',
    price: 1330.0,
    imageUrl: 'https://picsum.photos/400/300?random=17',
  },
  {
    title: 'Civic Sprint',
    brand: 'Civic Lab',
    description: 'Lightweight trainer; keywords: civic, rotor plate, civic mesh',
    price: 1380.0,
    imageUrl: 'https://picsum.photos/400/300?random=18',
  },
  {
    title: 'Civic Glide',
    brand: 'Civic Works',
    description: 'Daily comfort. Contains palindromes: civic, level, radar',
    price: 1440.0,
    imageUrl: 'https://picsum.photos/400/300?random=19',
  },
  {
    title: 'Rotor',
    brand: 'Rotor Performance',
    description: 'Edition inspired by rotor with level cushioning and radar grip',
    price: 1490.0,
    imageUrl: 'https://picsum.photos/400/300?random=20',
  },
  {
    title: 'Rotor Sprint',
    brand: 'Rotor Lab',
    description: 'Lightweight trainer; keywords: rotor, rotor plate, civic mesh',
    price: 1540.0,
    imageUrl: 'https://picsum.photos/400/300?random=21',
  },
  {
    title: 'Rotor Glide',
    brand: 'Rotor Works',
    description: 'Daily comfort. Contains palindromes: rotor, level, radar',
    price: 1600.0,
    imageUrl: 'https://picsum.photos/400/300?random=22',
  },
  {
    title: 'Kayak',
    brand: 'Kayak Performance',
    description: 'Edition inspired by kayak with level cushioning and radar grip',
    price: 1650.0,
    imageUrl: 'https://picsum.photos/400/300?random=23',
  },
  {
    title: 'Kayak Sprint',
    brand: 'Kayak Lab',
    description: 'Lightweight trainer; keywords: kayak, rotor plate, civic mesh',
    price: 1700.0,
    imageUrl: 'https://picsum.photos/400/300?random=24',
  },
  {
    title: 'Kayak Glide',
    brand: 'Kayak Works',
    description: 'Daily comfort. Contains palindromes: kayak, level, radar',
    price: 1760.0,
    imageUrl: 'https://picsum.photos/400/300?random=25',
  },
  {
    title: 'Madam',
    brand: 'Madam Performance',
    description: 'Edition inspired by madam with level cushioning and radar grip',
    price: 1810.0,
    imageUrl: 'https://picsum.photos/400/300?random=26',
  },
  {
    title: 'Madam Sprint',
    brand: 'Madam Lab',
    description: 'Lightweight trainer; keywords: madam, rotor plate, civic mesh',
    price: 1860.0,
    imageUrl: 'https://picsum.photos/400/300?random=27',
  },
  {
    title: 'Madam Glide',
    brand: 'Madam Works',
    description: 'Daily comfort. Contains palindromes: madam, level, radar',
    price: 1920.0,
    imageUrl: 'https://picsum.photos/400/300?random=28',
  },
  {
    title: 'Refer',
    brand: 'Refer Performance',
    description: 'Edition inspired by refer with level cushioning and radar grip',
    price: 1970.0,
    imageUrl: 'https://picsum.photos/400/300?random=29',
  },
  {
    title: 'Refer Sprint',
    brand: 'Refer Lab',
    description: 'Lightweight trainer; keywords: refer, rotor plate, civic mesh',
    price: 2020.0,
    imageUrl: 'https://picsum.photos/400/300?random=30',
  },
  {
    title: 'Refer Glide',
    brand: 'Refer Works',
    description: 'Daily comfort. Contains palindromes: refer, level, radar',
    price: 2080.0,
    imageUrl: 'https://picsum.photos/400/300?random=31',
  },
  {
    title: 'Racecar',
    brand: 'Racecar Performance',
    description: 'Edition inspired by racecar with level cushioning and radar grip',
    price: 2130.0,
    imageUrl: 'https://picsum.photos/400/300?random=32',
  },
  {
    title: 'Racecar Sprint',
    brand: 'Racecar Lab',
    description: 'Lightweight trainer; keywords: racecar, rotor plate, civic mesh',
    price: 2180.0,
    imageUrl: 'https://picsum.photos/400/300?random=33',
  },
  {
    title: 'Racecar Glide',
    brand: 'Racecar Works',
    description: 'Daily comfort. Contains palindromes: racecar, level, radar',
    price: 2240.0,
    imageUrl: 'https://picsum.photos/400/300?random=34',
  },
  {
    title: 'Tenet',
    brand: 'Tenet Performance',
    description: 'Edition inspired by tenet with level cushioning and radar grip',
    price: 2290.0,
    imageUrl: 'https://picsum.photos/400/300?random=35',
  },
  {
    title: 'Tenet Sprint',
    brand: 'Tenet Lab',
    description: 'Lightweight trainer; keywords: tenet, rotor plate, civic mesh',
    price: 2340.0,
    imageUrl: 'https://picsum.photos/400/300?random=36',
  },
  {
    title: 'Tenet Glide',
    brand: 'Tenet Works',
    description: 'Daily comfort. Contains palindromes: tenet, level, radar',
    price: 2400.0,
    imageUrl: 'https://picsum.photos/400/300?random=37',
  },
  {
    title: 'Reconocer',
    brand: 'Reconocer Performance',
    description: 'Edition inspired by reconocer with level cushioning and radar grip',
    price: 2450.0,
    imageUrl: 'https://picsum.photos/400/300?random=38',
  },
  {
    title: 'Reconocer Sprint',
    brand: 'Reconocer Lab',
    description: 'Lightweight trainer; keywords: reconocer, rotor plate, civic mesh',
    price: 2500.0,
    imageUrl: 'https://picsum.photos/400/300?random=39',
  },
  {
    title: 'Reconocer Glide',
    brand: 'Reconocer Works',
    description: 'Daily comfort. Contains palindromes: reconocer, level, radar',
    price: 2560.0,
    imageUrl: 'https://picsum.photos/400/300?random=40',
  },
  {
    title: 'Rotavator',
    brand: 'Rotavator Performance',
    description: 'Edition inspired by rotavator with level cushioning and radar grip',
    price: 2610.0,
    imageUrl: 'https://picsum.photos/400/300?random=41',
  },
  {
    title: 'Rotavator Sprint',
    brand: 'Rotavator Lab',
    description: 'Lightweight trainer; keywords: rotavator, rotor plate, civic mesh',
    price: 2660.0,
    imageUrl: 'https://picsum.photos/400/300?random=42',
  },
  {
    title: 'Rotavator Glide',
    brand: 'Rotavator Works',
    description: 'Daily comfort. Contains palindromes: rotavator, level, radar',
    price: 2720.0,
    imageUrl: 'https://picsum.photos/400/300?random=43',
  },
  {
    title: 'Repaper',
    brand: 'Repaper Performance',
    description: 'Edition inspired by repaper with level cushioning and radar grip',
    price: 2770.0,
    imageUrl: 'https://picsum.photos/400/300?random=44',
  },
  {
    title: 'Repaper Sprint',
    brand: 'Repaper Lab',
    description: 'Lightweight trainer; keywords: repaper, rotor plate, civic mesh',
    price: 2820.0,
    imageUrl: 'https://picsum.photos/400/300?random=45',
  },
  {
    title: 'Repaper Glide',
    brand: 'Repaper Works',
    description: 'Daily comfort. Contains palindromes: repaper, level, radar',
    price: 2880.0,
    imageUrl: 'https://picsum.photos/400/300?random=46',
  },
  {
    title: 'Reviver',
    brand: 'Reviver Performance',
    description: 'Edition inspired by reviver with level cushioning and radar grip',
    price: 2930.0,
    imageUrl: 'https://picsum.photos/400/300?random=47',
  },
  {
    title: 'Reviver Sprint',
    brand: 'Reviver Lab',
    description: 'Lightweight trainer; keywords: reviver, rotor plate, civic mesh',
    price: 2980.0,
    imageUrl: 'https://picsum.photos/400/300?random=48',
  },
  {
    title: 'Reviver Glide',
    brand: 'Reviver Works',
    description: 'Daily comfort. Contains palindromes: reviver, level, radar',
    price: 3040.0,
    imageUrl: 'https://picsum.photos/400/300?random=49',
  },
  {
    title: 'Noon',
    brand: 'Noon Performance',
    description: 'Edition inspired by noon with level cushioning and radar grip',
    price: 3090.0,
    imageUrl: 'https://picsum.photos/400/300?random=50',
  },
  {
    title: 'Noon Sprint',
    brand: 'Noon Lab',
    description: 'Lightweight trainer; keywords: noon, rotor plate, civic mesh',
    price: 3140.0,
    imageUrl: 'https://picsum.photos/400/300?random=51',
  },
  {
    title: 'Noon Glide',
    brand: 'Noon Works',
    description: 'Daily comfort. Contains palindromes: noon, level, radar',
    price: 620.0,
    imageUrl: 'https://picsum.photos/400/300?random=52',
  },
  {
    title: 'Stats',
    brand: 'Stats Performance',
    description: 'Edition inspired by stats with level cushioning and radar grip',
    price: 670.0,
    imageUrl: 'https://picsum.photos/400/300?random=53',
  },
  {
    title: 'Stats Sprint',
    brand: 'Stats Lab',
    description: 'Lightweight trainer; keywords: stats, rotor plate, civic mesh',
    price: 720.0,
    imageUrl: 'https://picsum.photos/400/300?random=54',
  },
  {
    title: 'Stats Glide',
    brand: 'Stats Works',
    description: 'Daily comfort. Contains palindromes: stats, level, radar',
    price: 770.0,
    imageUrl: 'https://picsum.photos/400/300?random=55',
  },
  {
    title: 'Sagas',
    brand: 'Sagas Performance',
    description: 'Edition inspired by sagas with level cushioning and radar grip',
    price: 820.0,
    imageUrl: 'https://picsum.photos/400/300?random=56',
  },
  {
    title: 'Sagas Sprint',
    brand: 'Sagas Lab',
    description: 'Lightweight trainer; keywords: sagas, rotor plate, civic mesh',
    price: 870.0,
    imageUrl: 'https://picsum.photos/400/300?random=57',
  },
  {
    title: 'Sagas Glide',
    brand: 'Sagas Works',
    description: 'Daily comfort. Contains palindromes: sagas, level, radar',
    price: 920.0,
    imageUrl: 'https://picsum.photos/400/300?random=58',
  },
  {
    title: 'Minim',
    brand: 'Minim Performance',
    description: 'Edition inspired by minim with level cushioning and radar grip',
    price: 970.0,
    imageUrl: 'https://picsum.photos/400/300?random=59',
  },
  {
    title: 'Minim Sprint',
    brand: 'Minim Lab',
    description: 'Lightweight trainer; keywords: minim, rotor plate, civic mesh',
    price: 1020.0,
    imageUrl: 'https://picsum.photos/400/300?random=60',
  },
  {
    title: 'Minim Glide',
    brand: 'Minim Works',
    description: 'Daily comfort. Contains palindromes: minim, level, radar',
    price: 1070.0,
    imageUrl: 'https://picsum.photos/400/300?random=61',
  },
  {
    title: 'Redivider',
    brand: 'Redivider Performance',
    description: 'Edition inspired by redivider with level cushioning and radar grip',
    price: 1120.0,
    imageUrl: 'https://picsum.photos/400/300?random=62',
  },
  {
    title: 'Redivider Sprint',
    brand: 'Redivider Lab',
    description: 'Lightweight trainer; keywords: redivider, rotor plate, civic mesh',
    price: 1170.0,
    imageUrl: 'https://picsum.photos/400/300?random=63',
  },
  {
    title: 'Redivider Glide',
    brand: 'Redivider Works',
    description: 'Daily comfort. Contains palindromes: redivider, level, radar',
    price: 1220.0,
    imageUrl: 'https://picsum.photos/400/300?random=64',
  },
  {
    title: 'Detartrated',
    brand: 'Detartrated Performance',
    description: 'Edition inspired by detartrated with level cushioning and radar grip',
    price: 1270.0,
    imageUrl: 'https://picsum.photos/400/300?random=65',
  },
  {
    title: 'Detartrated Sprint',
    brand: 'Detartrated Lab',
    description: 'Lightweight trainer; keywords: detartrated, rotor plate, civic mesh',
    price: 1320.0,
    imageUrl: 'https://picsum.photos/400/300?random=66',
  },
  {
    title: 'Detartrated Glide',
    brand: 'Detartrated Works',
    description: 'Daily comfort. Contains palindromes: detartrated, level, radar',
    price: 1370.0,
    imageUrl: 'https://picsum.photos/400/300?random=67',
  },
  {
    title: 'Malayalam',
    brand: 'Malayalam Performance',
    description: 'Edition inspired by malayalam with level cushioning and radar grip',
    price: 1420.0,
    imageUrl: 'https://picsum.photos/400/300?random=68',
  },
  {
    title: 'Malayalam Sprint',
    brand: 'Malayalam Lab',
    description: 'Lightweight trainer; keywords: malayalam, rotor plate, civic mesh',
    price: 1470.0,
    imageUrl: 'https://picsum.photos/400/300?random=69',
  },
  {
    title: 'Malayalam Glide',
    brand: 'Malayalam Works',
    description: 'Daily comfort. Contains palindromes: malayalam, level, radar',
    price: 1520.0,
    imageUrl: 'https://picsum.photos/400/300?random=70',
  },
  {
    title: 'Redder',
    brand: 'Redder Performance',
    description: 'Edition inspired by redder with level cushioning and radar grip',
    price: 1570.0,
    imageUrl: 'https://picsum.photos/400/300?random=71',
  },
  {
    title: 'Redder Sprint',
    brand: 'Redder Lab',
    description: 'Lightweight trainer; keywords: redder, rotor plate, civic mesh',
    price: 1620.0,
    imageUrl: 'https://picsum.photos/400/300?random=72',
  },
  {
    title: 'Redder Glide',
    brand: 'Redder Works',
    description: 'Daily comfort. Contains palindromes: redder, level, radar',
    price: 1670.0,
    imageUrl: 'https://picsum.photos/400/300?random=73',
  },
  {
    title: 'Deified',
    brand: 'Deified Performance',
    description: 'Edition inspired by deified with level cushioning and radar grip',
    price: 1720.0,
    imageUrl: 'https://picsum.photos/400/300?random=74',
  },
  {
    title: 'Deified Sprint',
    brand: 'Deified Lab',
    description: 'Lightweight trainer; keywords: deified, rotor plate, civic mesh',
    price: 1770.0,
    imageUrl: 'https://picsum.photos/400/300?random=75',
  },
  {
    title: 'Deified Glide',
    brand: 'Deified Works',
    description: 'Daily comfort. Contains palindromes: deified, level, radar',
    price: 1820.0,
    imageUrl: 'https://picsum.photos/400/300?random=76',
  },
  {
    title: 'Rotator',
    brand: 'Rotator Performance',
    description: 'Edition inspired by rotator with level cushioning and radar grip',
    price: 1870.0,
    imageUrl: 'https://picsum.photos/400/300?random=77',
  },
  {
    title: 'Rotator Sprint',
    brand: 'Rotator Lab',
    description: 'Lightweight trainer; keywords: rotator, rotor plate, civic mesh',
    price: 1920.0,
    imageUrl: 'https://picsum.photos/400/300?random=78',
  },
  {
    title: 'Rotator Glide',
    brand: 'Rotator Works',
    description: 'Daily comfort. Contains palindromes: rotator, level, radar',
    price: 1970.0,
    imageUrl: 'https://picsum.photos/400/300?random=79',
  },
  {
    title: 'Solos',
    brand: 'Solos Performance',
    description: 'Edition inspired by solos with level cushioning and radar grip',
    price: 2020.0,
    imageUrl: 'https://picsum.photos/400/300?random=80',
  },
  {
    title: 'Solos Sprint',
    brand: 'Solos Lab',
    description: 'Lightweight trainer; keywords: solos, rotor plate, civic mesh',
    price: 2070.0,
    imageUrl: 'https://picsum.photos/400/300?random=81',
  },
  {
    title: 'Solos Glide',
    brand: 'Solos Works',
    description: 'Daily comfort. Contains palindromes: solos, level, radar',
    price: 2120.0,
    imageUrl: 'https://picsum.photos/400/300?random=82',
  },
  {
    title: 'Hannah',
    brand: 'Hannah Performance',
    description: 'Edition inspired by hannah with level cushioning and radar grip',
    price: 2170.0,
    imageUrl: 'https://picsum.photos/400/300?random=83',
  },
  {
    title: 'Hannah Sprint',
    brand: 'Hannah Lab',
    description: 'Lightweight trainer; keywords: hannah, rotor plate, civic mesh',
    price: 2220.0,
    imageUrl: 'https://picsum.photos/400/300?random=84',
  },
  {
    title: 'Hannah Glide',
    brand: 'Hannah Works',
    description: 'Daily comfort. Contains palindromes: hannah, level, radar',
    price: 2270.0,
    imageUrl: 'https://picsum.photos/400/300?random=85',
  },
  {
    title: 'Anna',
    brand: 'Anna Performance',
    description: 'Edition inspired by anna with level cushioning and radar grip',
    price: 2320.0,
    imageUrl: 'https://picsum.photos/400/300?random=86',
  },
  {
    title: 'Anna Sprint',
    brand: 'Anna Lab',
    description: 'Lightweight trainer; keywords: anna, rotor plate, civic mesh',
    price: 2370.0,
    imageUrl: 'https://picsum.photos/400/300?random=87',
  },
  {
    title: 'Anna Glide',
    brand: 'Anna Works',
    description: 'Daily comfort. Contains palindromes: anna, level, radar',
    price: 2420.0,
    imageUrl: 'https://picsum.photos/400/300?random=88',
  },
  {
    title: 'Level-Radar Fusion',
    brand: 'Level & Radar Collective',
    description: 'Dual-palindrome pack: level + radar with level foam and radar outsole',
    price: 710.0,
    imageUrl: 'https://picsum.photos/400/300?random=89',
  },
  {
    title: 'Civic-Rotor Fusion',
    brand: 'Civic & Rotor Collective',
    description: 'Dual-palindrome pack: civic + rotor with level foam and radar outsole',
    price: 740.0,
    imageUrl: 'https://picsum.photos/400/300?random=90',
  },
  {
    title: 'Kayak-Madam Fusion',
    brand: 'Kayak & Madam Collective',
    description: 'Dual-palindrome pack: kayak + madam with level foam and radar outsole',
    price: 770.0,
    imageUrl: 'https://picsum.photos/400/300?random=91',
  },
  {
    title: 'Refer-Racecar Fusion',
    brand: 'Refer & Racecar Collective',
    description: 'Dual-palindrome pack: refer + racecar with level foam and radar outsole',
    price: 800.0,
    imageUrl: 'https://picsum.photos/400/300?random=92',
  },
  {
    title: 'Tenet-Reconocer Fusion',
    brand: 'Tenet & Reconocer Collective',
    description: 'Dual-palindrome pack: tenet + reconocer with level foam and radar outsole',
    price: 830.0,
    imageUrl: 'https://picsum.photos/400/300?random=93',
  },
  {
    title: 'Rotavator-Repaper Fusion',
    brand: 'Rotavator & Repaper Collective',
    description: 'Dual-palindrome pack: rotavator + repaper with level foam and radar outsole',
    price: 860.0,
    imageUrl: 'https://picsum.photos/400/300?random=94',
  },
  {
    title: 'Reviver-Noon Fusion',
    brand: 'Reviver & Noon Collective',
    description: 'Dual-palindrome pack: reviver + noon with level foam and radar outsole',
    price: 890.0,
    imageUrl: 'https://picsum.photos/400/300?random=95',
  },
  {
    title: 'Stats-Sagas Fusion',
    brand: 'Stats & Sagas Collective',
    description: 'Dual-palindrome pack: stats + sagas with level foam and radar outsole',
    price: 920.0,
    imageUrl: 'httpsum.photos/400/300?random=96',
  },
  {
    title: 'Minim-Redder Fusion',
    brand: 'Minim & Redder Collective',
    description: 'Dual-palindrome pack: minim + redder with level foam and radar outsole',
    price: 950.0,
    imageUrl: 'https://picsum.photos/400/300?random=97',
  },
  {
    title: 'Deified-Rotator Fusion',
    brand: 'Deified & Rotator Collective',
    description: 'Dual-palindrome pack: deified + rotator with level foam and radar outsole',
    price: 980.0,
    imageUrl: 'https://picsum.photos/400/300?random=98',
  },
  {
    title: 'Solos-Hannah Fusion',
    brand: 'Solos & Hannah Collective',
    description: 'Dual-palindrome pack: solos + hannah with level foam and radar outsole',
    price: 1010.0,
    imageUrl: 'https://picsum.photos/400/300?random=99',
  },
  {
    title: 'Anna-Abba Fusion',
    brand: 'Anna & Abba Collective',
    description: 'Dual-palindrome pack: anna + abba with level foam and radar outsole',
    price: 1040.0,
    imageUrl: 'https://picsum.photos/400/300?random=100',
  },
];
