export const seedProducts = [
  {
    title: 'Z-Runner',
    brand: 'Abba Sports',
    description: 'Light shoes with abba pattern',
    price: 1200.00,
  },
  {
    title: 'MoonDash',
    brand: 'Orbit',
    description: 'Comfort for daily running',
    price: 980.00,
  },
  {
    title: 'ABBA Pro',
    brand: 'Nordic',
    description: 'ABBA limited edition',
    price: 2500.00,
  },
  {
    title: 'Wave',
    brand: 'Coast',
    description: 'Casual sneakers',
    price: 800.00,
  },
  {
    title: 'Echo',
    brand: 'Rebound',
    description: 'High rebound midsole',
    price: 1600.00,
  },
  {
    title: 'Tango',
    brand: 'Dance',
    description: 'Designed for studio',
    price: 1100.00,
  },
  {
    title: 'abba',
    brand: 'Test Brand',
    description: 'Test product for palindrome testing',
    price: 500.00,
  },
  {
    title: 'ABBA One',
    brand: 'ABBA Performance',
    description: 'Edition inspired by abba with level cushioning and radar grip',
    price: 850.00,
  },
  {
    title: 'ABBA Sprint',
    brand: 'ABBA Lab',
    description: 'Lightweight trainer; keywords: abba, rotor plate, civic mesh',
    price: 900.00,
  },
  {
    title: 'ABBA Glide',
    brand: 'ABBA Works',
    description: 'Daily comfort. Contains palindromes: abba, level, radar',
    price: 960.00,
  },
  {
    title: 'Level',
    brand: 'Level Performance',
    description: 'Edition inspired by level with level cushioning and radar grip',
    price: 1010.00,
  },
  {
    title: 'Level Sprint',
    brand: 'Level Lab',
    description: 'Lightweight trainer; keywords: level, rotor plate, civic mesh',
    price: 1060.00,
  },
  {
    title: 'Level Glide',
    brand: 'Level Works',
    description: 'Daily comfort. Contains palindromes: level, level, radar',
    price: 1120.00,
  },
  {
    title: 'Radar',
    brand: 'Radar Performance',
    description: 'Edition inspired by radar with level cushioning and radar grip',
    price: 1170.00,
  },
  {
    title: 'Radar Sprint',
    brand: 'Radar Lab',
    description: 'Lightweight trainer; keywords: radar, rotor plate, civic mesh',
    price: 1220.00,
  },
  {
    title: 'Radar Glide',
    brand: 'Radar Works',
    description: 'Daily comfort. Contains palindromes: radar, level, radar',
    price: 1280.00,
  },
  {
    title: 'Civic',
    brand: 'Civic Performance',
    description: 'Edition inspired by civic with level cushioning and radar grip',
    price: 1330.00,
  },
  {
    title: 'Civic Sprint',
    brand: 'Civic Lab',
    description: 'Lightweight trainer; keywords: civic, rotor plate, civic mesh',
    price: 1380.00,
  },
  {
    title: 'Civic Glide',
    brand: 'Civic Works',
    description: 'Daily comfort. Contains palindromes: civic, level, radar',
    price: 1440.00,
  },
  {
    title: 'Rotor',
    brand: 'Rotor Performance',
    description: 'Edition inspired by rotor with level cushioning and radar grip',
    price: 1490.00,
  },
  {
    title: 'Rotor Sprint',
    brand: 'Rotor Lab',
    description: 'Lightweight trainer; keywords: rotor, rotor plate, civic mesh',
    price: 1540.00,
  },
  {
    title: 'Rotor Glide',
    brand: 'Rotor Works',
    description: 'Daily comfort. Contains palindromes: rotor, level, radar',
    price: 1600.00,
  },
  {
    title: 'Kayak',
    brand: 'Kayak Performance',
    description: 'Edition inspired by kayak with level cushioning and radar grip',
    price: 1650.00,
  },
  {
    title: 'Kayak Sprint',
    brand: 'Kayak Lab',
    description: 'Lightweight trainer; keywords: kayak, rotor plate, civic mesh',
    price: 1700.00,
  },
  {
    title: 'Kayak Glide',
    brand: 'Kayak Works',
    description: 'Daily comfort. Contains palindromes: kayak, level, radar',
    price: 1760.00,
  },
  {
    title: 'Madam',
    brand: 'Madam Performance',
    description: 'Edition inspired by madam with level cushioning and radar grip',
    price: 1810.00,
  },
  {
    title: 'Madam Sprint',
    brand: 'Madam Lab',
    description: 'Lightweight trainer; keywords: madam, rotor plate, civic mesh',
    price: 1860.00,
  },
  {
    title: 'Madam Glide',
    brand: 'Madam Works',
    description: 'Daily comfort. Contains palindromes: madam, level, radar',
    price: 1920.00,
  },
  {
    title: 'Refer',
    brand: 'Refer Performance',
    description: 'Edition inspired by refer with level cushioning and radar grip',
    price: 1970.00,
  },
  {
    title: 'Refer Sprint',
    brand: 'Refer Lab',
    description: 'Lightweight trainer; keywords: refer, rotor plate, civic mesh',
    price: 2020.00,
  },
  {
    title: 'Refer Glide',
    brand: 'Refer Works',
    description: 'Daily comfort. Contains palindromes: refer, level, radar',
    price: 2080.00,
  },
  {
    title: 'Racecar',
    brand: 'Racecar Performance',
    description: 'Edition inspired by racecar with level cushioning and radar grip',
    price: 2130.00,
  },
  {
    title: 'Racecar Sprint',
    brand: 'Racecar Lab',
    description: 'Lightweight trainer; keywords: racecar, rotor plate, civic mesh',
    price: 2180.00,
  },
  {
    title: 'Racecar Glide',
    brand: 'Racecar Works',
    description: 'Daily comfort. Contains palindromes: racecar, level, radar',
    price: 2240.00,
  },
  {
    title: 'Tenet',
    brand: 'Tenet Performance',
    description: 'Edition inspired by tenet with level cushioning and radar grip',
    price: 2290.00,
  },
  {
    title: 'Tenet Sprint',
    brand: 'Tenet Lab',
    description: 'Lightweight trainer; keywords: tenet, rotor plate, civic mesh',
    price: 2340.00,
  },
  {
    title: 'Tenet Glide',
    brand: 'Tenet Works',
    description: 'Daily comfort. Contains palindromes: tenet, level, radar',
    price: 2400.00,
  },
  {
    title: 'Reconocer',
    brand: 'Reconocer Performance',
    description: 'Edition inspired by reconocer with level cushioning and radar grip',
    price: 2450.00,
  },
  {
    title: 'Reconocer Sprint',
    brand: 'Reconocer Lab',
    description: 'Lightweight trainer; keywords: reconocer, rotor plate, civic mesh',
    price: 2500.00,
  },
  {
    title: 'Reconocer Glide',
    brand: 'Reconocer Works',
    description: 'Daily comfort. Contains palindromes: reconocer, level, radar',
    price: 2560.00,
  },
  {
    title: 'Rotavator',
    brand: 'Rotavator Performance',
    description: 'Edition inspired by rotavator with level cushioning and radar grip',
    price: 2610.00,
  },
  {
    title: 'Rotavator Sprint',
    brand: 'Rotavator Lab',
    description: 'Lightweight trainer; keywords: rotavator, rotor plate, civic mesh',
    price: 2660.00,
  },
  {
    title: 'Rotavator Glide',
    brand: 'Rotavator Works',
    description: 'Daily comfort. Contains palindromes: rotavator, level, radar',
    price: 2720.00,
  },
  {
    title: 'Repaper',
    brand: 'Repaper Performance',
    description: 'Edition inspired by repaper with level cushioning and radar grip',
    price: 2770.00,
  },
  {
    title: 'Repaper Sprint',
    brand: 'Repaper Lab',
    description: 'Lightweight trainer; keywords: repaper, rotor plate, civic mesh',
    price: 2820.00,
  },
  {
    title: 'Repaper Glide',
    brand: 'Repaper Works',
    description: 'Daily comfort. Contains palindromes: repaper, level, radar',
    price: 2880.00,
  },
  {
    title: 'Reviver',
    brand: 'Reviver Performance',
    description: 'Edition inspired by reviver with level cushioning and radar grip',
    price: 2930.00,
  },
  {
    title: 'Reviver Sprint',
    brand: 'Reviver Lab',
    description: 'Lightweight trainer; keywords: reviver, rotor plate, civic mesh',
    price: 2980.00,
  },
  {
    title: 'Reviver Glide',
    brand: 'Reviver Works',
    description: 'Daily comfort. Contains palindromes: reviver, level, radar',
    price: 3040.00,
  },
  {
    title: 'Noon',
    brand: 'Noon Performance',
    description: 'Edition inspired by noon with level cushioning and radar grip',
    price: 3090.00,
  },
  {
    title: 'Noon Sprint',
    brand: 'Noon Lab',
    description: 'Lightweight trainer; keywords: noon, rotor plate, civic mesh',
    price: 3140.00,
  },
  {
    title: 'Noon Glide',
    brand: 'Noon Works',
    description: 'Daily comfort. Contains palindromes: noon, level, radar',
    price: 620.00,
  },
  {
    title: 'Stats',
    brand: 'Stats Performance',
    description: 'Edition inspired by stats with level cushioning and radar grip',
    price: 670.00,
  },
  {
    title: 'Stats Sprint',
    brand: 'Stats Lab',
    description: 'Lightweight trainer; keywords: stats, rotor plate, civic mesh',
    price: 720.00,
  },
  {
    title: 'Stats Glide',
    brand: 'Stats Works',
    description: 'Daily comfort. Contains palindromes: stats, level, radar',
    price: 770.00,
  },
  {
    title: 'Sagas',
    brand: 'Sagas Performance',
    description: 'Edition inspired by sagas with level cushioning and radar grip',
    price: 820.00,
  },
  {
    title: 'Sagas Sprint',
    brand: 'Sagas Lab',
    description: 'Lightweight trainer; keywords: sagas, rotor plate, civic mesh',
    price: 870.00,
  },
  {
    title: 'Sagas Glide',
    brand: 'Sagas Works',
    description: 'Daily comfort. Contains palindromes: sagas, level, radar',
    price: 920.00,
  },
  {
    title: 'Minim',
    brand: 'Minim Performance',
    description: 'Edition inspired by minim with level cushioning and radar grip',
    price: 970.00,
  },
  {
    title: 'Minim Sprint',
    brand: 'Minim Lab',
    description: 'Lightweight trainer; keywords: minim, rotor plate, civic mesh',
    price: 1020.00,
  },
  {
    title: 'Minim Glide',
    brand: 'Minim Works',
    description: 'Daily comfort. Contains palindromes: minim, level, radar',
    price: 1070.00,
  },
  {
    title: 'Redivider',
    brand: 'Redivider Performance',
    description: 'Edition inspired by redivider with level cushioning and radar grip',
    price: 1120.00,
  },
  {
    title: 'Redivider Sprint',
    brand: 'Redivider Lab',
    description: 'Lightweight trainer; keywords: redivider, rotor plate, civic mesh',
    price: 1170.00,
  },
  {
    title: 'Redivider Glide',
    brand: 'Redivider Works',
    description: 'Daily comfort. Contains palindromes: redivider, level, radar',
    price: 1220.00,
  },
  {
    title: 'Detartrated',
    brand: 'Detartrated Performance',
    description: 'Edition inspired by detartrated with level cushioning and radar grip',
    price: 1270.00,
  },
  {
    title: 'Detartrated Sprint',
    brand: 'Detartrated Lab',
    description: 'Lightweight trainer; keywords: detartrated, rotor plate, civic mesh',
    price: 1320.00,
  },
  {
    title: 'Detartrated Glide',
    brand: 'Detartrated Works',
    description: 'Daily comfort. Contains palindromes: detartrated, level, radar',
    price: 1370.00,
  },
  {
    title: 'Malayalam',
    brand: 'Malayalam Performance',
    description: 'Edition inspired by malayalam with level cushioning and radar grip',
    price: 1420.00,
  },
  {
    title: 'Malayalam Sprint',
    brand: 'Malayalam Lab',
    description: 'Lightweight trainer; keywords: malayalam, rotor plate, civic mesh',
    price: 1470.00,
  },
  {
    title: 'Malayalam Glide',
    brand: 'Malayalam Works',
    description: 'Daily comfort. Contains palindromes: malayalam, level, radar',
    price: 1520.00,
  },
  {
    title: 'Redder',
    brand: 'Redder Performance',
    description: 'Edition inspired by redder with level cushioning and radar grip',
    price: 1570.00,
  },
  {
    title: 'Redder Sprint',
    brand: 'Redder Lab',
    description: 'Lightweight trainer; keywords: redder, rotor plate, civic mesh',
    price: 1620.00,
  },
  {
    title: 'Redder Glide',
    brand: 'Redder Works',
    description: 'Daily comfort. Contains palindromes: redder, level, radar',
    price: 1670.00,
  },
  {
    title: 'Deified',
    brand: 'Deified Performance',
    description: 'Edition inspired by deified with level cushioning and radar grip',
    price: 1720.00,
  },
  {
    title: 'Deified Sprint',
    brand: 'Deified Lab',
    description: 'Lightweight trainer; keywords: deified, rotor plate, civic mesh',
    price: 1770.00,
  },
  {
    title: 'Deified Glide',
    brand: 'Deified Works',
    description: 'Daily comfort. Contains palindromes: deified, level, radar',
    price: 1820.00,
  },
  {
    title: 'Rotator',
    brand: 'Rotator Performance',
    description: 'Edition inspired by rotator with level cushioning and radar grip',
    price: 1870.00,
  },
  {
    title: 'Rotator Sprint',
    brand: 'Rotator Lab',
    description: 'Lightweight trainer; keywords: rotator, rotor plate, civic mesh',
    price: 1920.00,
  },
  {
    title: 'Rotator Glide',
    brand: 'Rotator Works',
    description: 'Daily comfort. Contains palindromes: rotator, level, radar',
    price: 1970.00,
  },
  {
    title: 'Solos',
    brand: 'Solos Performance',
    description: 'Edition inspired by solos with level cushioning and radar grip',
    price: 2020.00,
  },
  {
    title: 'Solos Sprint',
    brand: 'Solos Lab',
    description: 'Lightweight trainer; keywords: solos, rotor plate, civic mesh',
    price: 2070.00,
  },
  {
    title: 'Solos Glide',
    brand: 'Solos Works',
    description: 'Daily comfort. Contains palindromes: solos, level, radar',
    price: 2120.00,
  },
  {
    title: 'Hannah',
    brand: 'Hannah Performance',
    description: 'Edition inspired by hannah with level cushioning and radar grip',
    price: 2170.00,
  },
  {
    title: 'Hannah Sprint',
    brand: 'Hannah Lab',
    description: 'Lightweight trainer; keywords: hannah, rotor plate, civic mesh',
    price: 2220.00,
  },
  {
    title: 'Hannah Glide',
    brand: 'Hannah Works',
    description: 'Daily comfort. Contains palindromes: hannah, level, radar',
    price: 2270.00,
  },
  {
    title: 'Anna',
    brand: 'Anna Performance',
    description: 'Edition inspired by anna with level cushioning and radar grip',
    price: 2320.00,
  },
  {
    title: 'Anna Sprint',
    brand: 'Anna Lab',
    description: 'Lightweight trainer; keywords: anna, rotor plate, civic mesh',
    price: 2370.00,
  },
  {
    title: 'Anna Glide',
    brand: 'Anna Works',
    description: 'Daily comfort. Contains palindromes: anna, level, radar',
    price: 2420.00,
  },
  {
    title: 'Level-Radar Fusion',
    brand: 'Level & Radar Collective',
    description: 'Dual-palindrome pack: level + radar with level foam and radar outsole',
    price: 710.00,
  },
  {
    title: 'Civic-Rotor Fusion',
    brand: 'Civic & Rotor Collective',
    description: 'Dual-palindrome pack: civic + rotor with level foam and radar outsole',
    price: 740.00,
  },
  {
    title: 'Kayak-Madam Fusion',
    brand: 'Kayak & Madam Collective',
    description: 'Dual-palindrome pack: kayak + madam with level foam and radar outsole',
    price: 770.00,
  },
  {
    title: 'Refer-Racecar Fusion',
    brand: 'Refer & Racecar Collective',
    description: 'Dual-palindrome pack: refer + racecar with level foam and radar outsole',
    price: 800.00,
  },
  {
    title: 'Tenet-Reconocer Fusion',
    brand: 'Tenet & Reconocer Collective',
    description: 'Dual-palindrome pack: tenet + reconocer with level foam and radar outsole',
    price: 830.00,
  },
  {
    title: 'Rotavator-Repaper Fusion',
    brand: 'Rotavator & Repaper Collective',
    description: 'Dual-palindrome pack: rotavator + repaper with level foam and radar outsole',
    price: 860.00,
  },
  {
    title: 'Reviver-Noon Fusion',
    brand: 'Reviver & Noon Collective',
    description: 'Dual-palindrome pack: reviver + noon with level foam and radar outsole',
    price: 890.00,
  },
  {
    title: 'Stats-Sagas Fusion',
    brand: 'Stats & Sagas Collective',
    description: 'Dual-palindrome pack: stats + sagas with level foam and radar outsole',
    price: 920.00,
  },
  {
    title: 'Minim-Redder Fusion',
    brand: 'Minim & Redder Collective',
    description: 'Dual-palindrome pack: minim + redder with level foam and radar outsole',
    price: 950.00,
  },
  {
    title: 'Deified-Rotator Fusion',
    brand: 'Deified & Rotator Collective',
    description: 'Dual-palindrome pack: deified + rotator with level foam and radar outsole',
    price: 980.00,
  },
  {
    title: 'Solos-Hannah Fusion',
    brand: 'Solos & Hannah Collective',
    description: 'Dual-palindrome pack: solos + hannah with level foam and radar outsole',
    price: 1010.00,
  },
  {
    title: 'Anna-Abba Fusion',
    brand: 'Anna & Abba Collective',
    description: 'Dual-palindrome pack: anna + abba with level foam and radar outsole',
    price: 1040.00,
  },
];
